### ISSUE TITLE
The "search_string_length" ping wrongly takes the characters number value of the previous accessed URL, after opening a new tab

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/federated-learning-v2-study-addon#11]
[Affected versions]:
- Unbranded Firefox 66.0b14

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]
- Have a new Firefox profile created.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to "about:telemetry" page.
2. Drag and drop the .xpi in the tab strip.
3. Open a new tab.
4. Switch to "about:telemetry" page and reload it.
5. Select the archived experiment-specific pings.
6. Observe the "search_string_length" value.

[Expected result]:
- The value is "0"

[Actual result]:
- The value is "101".

[Notes]:
- This is reproducible with all branches.
- Here is a screen recording of the issue:

![new tab](https://user-images.githubusercontent.com/26000308/54297927-7aee8480-45c0-11e9-839c-3a21237c5970.gif)

**Comment by motin** [comment]
Closing this since:
* It is expected behavior (the search_string_length should reflect the character length of what is visible in the awesome bar)
* This is an uncommon edge-case
* Noting that ´search_string_length´ indeed is not a good proxy for number of characters entered (as implemented in v1), we added `num_key_down_events` in v2 which will be the primary proxy for energy consumed before ending an interaction.

**Comment by SoftVision-PaulOiegas** [comment]
Hi @motin 
>It is expected behavior (the search_string_length should reflect the character length of what is visible in the awesome bar)
> This is an uncommon edge-case

We can understand this, but does not seem to be an edge case. A new ping is automatically generated if you already have a website loaded and you open a new tab and close it. This seems very likely to be encountered.
However, if you think that this won't affect the metrics of the study, then we're ok too. We just want to make sure that we're not omitting a valid concern.
