### ISSUE TITLE
Pressing the "ESC" key while the address bar is focused doesn't generate any pings specific to the experiment

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/federated-learning-v2-study-addon#12]
[Affected versions]:
- Unbranded Firefox 66.0b14

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]
- Have a new Firefox profile created.
- The latest Federated Learning V2 add-on is installed.
- You are enrolled in the "control" branch.
- A local server is set up.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites.
2. Open a new tab.
3. Press ESC key.
4. Observe the pings folder from the local server.

[Expected result]:
- The "frecency_update" and "shield-study-addon" pings are displayed.

[Actual result]:
- There is no ping generated.

[Notes]:
- This is reproducible with all branches.
- Here is a screen recording of the issue:

![esc key](https://user-images.githubusercontent.com/26000308/54298768-116f7580-45c2-11e9-9a47-ddb6939699aa.gif)

**Comment by motin** [comment]
Closing this since pressing ESC in the awesome bar is not a signal for the end of an awesome bar interaction (rather it can be seen as a precursor to entering new text / starting a new search since the previous one was not sufficient). Note: the keypress is indirectly registered as part of the `num_key_down_events` telemetry property once the awesome bar interaction is concluded.
