### ISSUE TITLE
The experiment remains enabled after setting the permanent private browsing mode

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/federated-learning-v2-study-addon#8]
[Affected versions]:
- Unbranded Firefox 66.0b14

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]
- Have a new Firefox profile created.
- The latest [Federated Learning V2 add-on](https://bugzilla.mozilla.org/show_bug.cgi?id=1532217#c6) is installed.
- You are enrolled in the "dogfooding" branch.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites.
2. Navigate to "about:preferences#privacy" page.
3. Select "Never remember history" option.
4. Restart the browser.
5. Navigate to "about:support" page and observe if the experiment is still enabled.

[Expected result]:
- The experiment is no longer enabled.

[Actual result]:
- The experiment is still enabled.

[Notes]:
- This is reproducible with all branches.
- Here is a screen recording of the issue:

![uninstall private](https://user-images.githubusercontent.com/26000308/54140326-0edb1780-442c-11e9-8c3c-d6ff01210797.gif)

**Comment by motin** [comment]
Thanks, I see that the test plan included this test case albeit for this study we have deemed it enough to check permanent private browsing only at study enrollment time and not after every restart. During private browsing, we inactivate all study-related instrumentation and lie dormant until expiration or until the user disables permanent private browsing. 

Of course, if the user opts out of studies in general, Normandy will end the study and uninstall the add-on.

Fixed by [updating the test instructions](https://github.com/mozilla/federated-learning-v2-study-addon/commit/c1e5ab7cf74c8cdbf81cd15808a1948f0181fe65).
